package assignment;

import Assignment_Class.Module_Class;
import javax.swing.JOptionPane;

public class AddModule extends javax.swing.JFrame {

    /**
     * Creates new form AddModule
     */
    public AddModule() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        D_AddModule = new javax.swing.JLabel();
        ChooseProgram = new javax.swing.JComboBox<>();
        D_Program = new javax.swing.JLabel();
        D_EnterModuleName = new javax.swing.JLabel();
        ModuleName = new javax.swing.JTextField();
        A_Backbtn = new javax.swing.JButton();
        A_ClearBtn = new javax.swing.JButton();
        A_EnterBtn = new javax.swing.JButton();
        D_Intake = new javax.swing.JLabel();
        ChooseIntake = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        D_AddModule.setFont(new java.awt.Font("Cooper Black", 0, 48)); // NOI18N
        D_AddModule.setText("Add Module");

        ChooseProgram.setFont(new java.awt.Font("Cooper Black", 0, 16)); // NOI18N
        ChooseProgram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science (CS)", "Business Information System (BIS)" }));
        ChooseProgram.setToolTipText("");

        D_Program.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_Program.setText("Program :");

        D_EnterModuleName.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_EnterModuleName.setText("Enter Module Name :");

        ModuleName.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        ModuleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModuleNameActionPerformed(evt);
            }
        });

        A_Backbtn.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        A_Backbtn.setText("Back");
        A_Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_BackbtnActionPerformed(evt);
            }
        });

        A_ClearBtn.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        A_ClearBtn.setText("Clear");
        A_ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_ClearBtnActionPerformed(evt);
            }
        });

        A_EnterBtn.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        A_EnterBtn.setText("Enter");
        A_EnterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_EnterBtnActionPerformed(evt);
            }
        });

        D_Intake.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_Intake.setText("Intake : ");

        ChooseIntake.setFont(new java.awt.Font("Cooper Black", 0, 16)); // NOI18N
        ChooseIntake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year 1", "Year 2", "Year 3", "Year 4" }));
        ChooseIntake.setToolTipText("");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(D_AddModule)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(D_Program)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ChooseProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(D_Intake)
                        .addGap(35, 35, 35)
                        .addComponent(ChooseIntake, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ModuleName, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(A_EnterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(A_ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(A_Backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(D_EnterModuleName))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(D_AddModule)
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChooseProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D_Program))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ChooseIntake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D_Intake))
                .addGap(35, 35, 35)
                .addComponent(D_EnterModuleName)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ModuleName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(A_ClearBtn)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(A_Backbtn))
                        .addComponent(A_EnterBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModuleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModuleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModuleNameActionPerformed

    private void A_BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_BackbtnActionPerformed
        ManageLearningModule mld = new ManageLearningModule();
        mld.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_A_BackbtnActionPerformed

    private void A_ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_ClearBtnActionPerformed
        ModuleName.setText("");     
    }//GEN-LAST:event_A_ClearBtnActionPerformed

    private void A_EnterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_EnterBtnActionPerformed
        
        Module_Class mc= new Module_Class();
        
        String program = ChooseProgram.getSelectedItem().toString();       
        String modulename = ModuleName.getText();
        String Filename = program + ".txt";
        
        mc.setProgram(program);
        mc.setIntake(ChooseIntake.getSelectedItem().toString());
        mc.setModulename(modulename);
  
        try{
            mc.AddModule(Filename, modulename);
            
            JOptionPane.showMessageDialog(rootPane, "Module Add Successfully");
            ModuleName.setText("");
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Something Wrong!\nPlease try again!");
            ModuleName.setText("");
        }
    }//GEN-LAST:event_A_EnterBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddModule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_Backbtn;
    private javax.swing.JButton A_ClearBtn;
    private javax.swing.JButton A_EnterBtn;
    private javax.swing.JComboBox<String> ChooseIntake;
    private javax.swing.JComboBox<String> ChooseProgram;
    private javax.swing.JLabel D_AddModule;
    private javax.swing.JLabel D_EnterModuleName;
    private javax.swing.JLabel D_Intake;
    private javax.swing.JLabel D_Program;
    private javax.swing.JTextField ModuleName;
    // End of variables declaration//GEN-END:variables
}
