
package assignment;

public class Administrator_Page extends javax.swing.JFrame{

    /**
     * Creates new form Administrator_Page
     */
    public Administrator_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        D_AdminFunction1Btn = new javax.swing.JButton();
        D_AdminFunction2Btn = new javax.swing.JButton();
        D_Welcome = new javax.swing.JLabel();
        A_Backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        D_AdminFunction1Btn.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_AdminFunction1Btn.setText("Manage Learning Modules");
        D_AdminFunction1Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_AdminFunction1BtnActionPerformed(evt);
            }
        });

        D_AdminFunction2Btn.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_AdminFunction2Btn.setText("Manage Student Enrolments ");
        D_AdminFunction2Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_AdminFunction2BtnActionPerformed(evt);
            }
        });

        D_Welcome.setFont(new java.awt.Font("Cooper Black", 0, 48)); // NOI18N
        D_Welcome.setText("Welcome");

        A_Backbtn.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        A_Backbtn.setText("Back");
        A_Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_BackbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(A_Backbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_AdminFunction2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(D_AdminFunction1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 403, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(D_Welcome)))
                .addContainerGap(65, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(D_Welcome)
                .addGap(38, 38, 38)
                .addComponent(D_AdminFunction1Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(D_AdminFunction2Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addComponent(A_Backbtn)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void D_AdminFunction1BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_AdminFunction1BtnActionPerformed
        ManageLearningModule mld= new ManageLearningModule();
        mld.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D_AdminFunction1BtnActionPerformed

    private void D_AdminFunction2BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_AdminFunction2BtnActionPerformed
        ManageStudentEnrolment mse= new ManageStudentEnrolment();
        mse.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D_AdminFunction2BtnActionPerformed

    private void A_BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_BackbtnActionPerformed
        Login_Administrators la = new Login_Administrators();
        la.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_A_BackbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Administrator_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Administrator_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Administrator_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Administrator_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Administrator_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_Backbtn;
    private javax.swing.JButton D_AdminFunction1Btn;
    private javax.swing.JButton D_AdminFunction2Btn;
    private javax.swing.JLabel D_Welcome;
    // End of variables declaration//GEN-END:variables
}
