
package assignment;

import Assignment_Class.Module_Class;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

public class DeleteModule extends javax.swing.JFrame {

    DefaultListModel<String> listModel;
   
    public DeleteModule() {
        initComponents();
        listModel = new DefaultListModel<>();
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ChooseProgram = new javax.swing.JComboBox<>();
        D_Program = new javax.swing.JLabel();
        D_Intake = new javax.swing.JLabel();
        D_EnterModuleName = new javax.swing.JLabel();
        ChooseIntake = new javax.swing.JComboBox<>();
        ModuleName = new javax.swing.JTextField();
        A_Backbtn = new javax.swing.JButton();
        A_ClearBtn = new javax.swing.JButton();
        A_DeleteBtn = new javax.swing.JButton();
        D_DeleteModule = new javax.swing.JLabel();
        A_ShowModuleBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        ShowModule = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        ChooseProgram.setFont(new java.awt.Font("Cooper Black", 0, 16)); // NOI18N
        ChooseProgram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science (CS)", "Business Information System (BIS)" }));
        ChooseProgram.setToolTipText("");

        D_Program.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_Program.setText("Program :");

        D_Intake.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_Intake.setText("Intake : ");

        D_EnterModuleName.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_EnterModuleName.setText("Enter Module Name :");

        ChooseIntake.setFont(new java.awt.Font("Cooper Black", 0, 16)); // NOI18N
        ChooseIntake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year 1", "Year 2", "Year 3", "Year 4" }));
        ChooseIntake.setToolTipText("");

        ModuleName.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        ModuleName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModuleNameActionPerformed(evt);
            }
        });

        A_Backbtn.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        A_Backbtn.setText("Back");
        A_Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_BackbtnActionPerformed(evt);
            }
        });

        A_ClearBtn.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        A_ClearBtn.setText("Clear");
        A_ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_ClearBtnActionPerformed(evt);
            }
        });

        A_DeleteBtn.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        A_DeleteBtn.setText("Delete");
        A_DeleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_DeleteBtnActionPerformed(evt);
            }
        });

        D_DeleteModule.setFont(new java.awt.Font("Cooper Black", 0, 48)); // NOI18N
        D_DeleteModule.setText("Delete Module");

        A_ShowModuleBtn.setFont(new java.awt.Font("Cooper Black", 0, 16)); // NOI18N
        A_ShowModuleBtn.setText("Liat All Module");
        A_ShowModuleBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_ShowModuleBtnActionPerformed(evt);
            }
        });

        ShowModule.setColumns(20);
        ShowModule.setRows(5);
        jScrollPane1.setViewportView(ShowModule);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ModuleName, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A_ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(A_Backbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(A_DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_Program)
                            .addComponent(D_Intake))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ChooseIntake, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ChooseProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(D_EnterModuleName)
                    .addComponent(D_DeleteModule))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A_ShowModuleBtn))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(D_DeleteModule)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(D_Program)
                            .addComponent(ChooseProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(D_Intake)
                            .addComponent(ChooseIntake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(D_EnterModuleName)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ModuleName, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(A_DeleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(A_ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(A_Backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(A_ShowModuleBtn))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ModuleNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModuleNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ModuleNameActionPerformed

    private void A_BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_BackbtnActionPerformed
        ManageLearningModule mld = new ManageLearningModule();
        mld.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_A_BackbtnActionPerformed

    private void A_ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_ClearBtnActionPerformed
        ModuleName.setText("");
    }//GEN-LAST:event_A_ClearBtnActionPerformed

    private void A_DeleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_DeleteBtnActionPerformed
        
        Module_Class mc = new Module_Class();
        String delete = ModuleName.getText();
        String program = ChooseProgram.getSelectedItem().toString();       
        String Filename = program + ".txt";
        try{
            Boolean status = mc.DeleteModule(Filename,delete);
            if (status) {
                JOptionPane.showMessageDialog(rootPane, "Module Deleted");
            } else {
                JOptionPane.showMessageDialog(rootPane, "Module not Found");
            }
            ModuleName.setText("");     
            
        }catch(Exception e){
            Logger.getLogger(DeleteModule.class.getName()).log(Level.SEVERE, null, e);
        }    

    }//GEN-LAST:event_A_DeleteBtnActionPerformed

    private void A_ShowModuleBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_ShowModuleBtnActionPerformed
            
        String program = ChooseProgram.getSelectedItem().toString();
        String intake = ChooseIntake.getSelectedItem().toString();
        String temp =  "text.txt";
        String Filename = program + ".txt";
        File tempfile = new File(temp);

        String rl=null;
        StringBuilder bf = new StringBuilder();
        try {
            FileReader fr = new FileReader(Filename);
            BufferedReader br= new BufferedReader(fr);
            while((rl=br.readLine())!= null){
                rl=rl.trim();
                if(rl.indexOf(intake) != -1){bf.append(rl).append("\r\n");}
            }
            br.close();
            FileWriter fw =new FileWriter(temp);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(bf.toString());
            bw.flush();
            bw.close();
            FileReader fr2 = new FileReader(new File(temp));
            BufferedReader br2 =new BufferedReader(fr2);
            ShowModule.read(br2, null);
            br.close();
            ShowModule.requestFocus();
            tempfile.deleteOnExit();
            
        
        } catch (IOException ex) {
            Logger.getLogger(DeleteModule.class.getName()).log(Level.SEVERE, null, ex);
        }
          
    }//GEN-LAST:event_A_ShowModuleBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteModule.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteModule().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_Backbtn;
    private javax.swing.JButton A_ClearBtn;
    private javax.swing.JButton A_DeleteBtn;
    private javax.swing.JButton A_ShowModuleBtn;
    private javax.swing.JComboBox<String> ChooseIntake;
    private javax.swing.JComboBox<String> ChooseProgram;
    private javax.swing.JLabel D_DeleteModule;
    private javax.swing.JLabel D_EnterModuleName;
    private javax.swing.JLabel D_Intake;
    private javax.swing.JLabel D_Program;
    private javax.swing.JTextField ModuleName;
    private javax.swing.JTextArea ShowModule;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
