
package assignment;

import Assignment_Class.Student_Class;
import java.util.List;
import java.io.*;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import java.util.Scanner;

public class EditStudent extends javax.swing.JFrame {

    /**
     * Creates new form EditStudent
     */
    public EditStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        D_EnterStudentID = new javax.swing.JLabel();
        StudentID = new javax.swing.JTextField();
        A_Backbtn = new javax.swing.JButton();
        A_Searchbtn = new javax.swing.JButton();
        D_EditStudent = new javax.swing.JLabel();
        A_EditBtn = new javax.swing.JButton();
        D_Gender = new javax.swing.JLabel();
        D_Email = new javax.swing.JLabel();
        D_Age = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        StudentName = new javax.swing.JTextField();
        D_ICPassPortNumber = new javax.swing.JLabel();
        Age = new javax.swing.JTextField();
        ICPassPortNumber = new javax.swing.JTextField();
        Gender = new javax.swing.JTextField();
        D_Program = new javax.swing.JLabel();
        ProgramComboBox = new javax.swing.JComboBox<>();
        D_Intake = new javax.swing.JLabel();
        IntakeComboBox = new javax.swing.JComboBox<>();
        D_PhoneNumber = new javax.swing.JLabel();
        D_StudentName = new javax.swing.JLabel();
        PhoneNumber = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        D_EnterStudentID.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_EnterStudentID.setText("Enter Student ID : ");

        StudentID.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        StudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentIDActionPerformed(evt);
            }
        });

        A_Backbtn.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        A_Backbtn.setText("Back");
        A_Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_BackbtnActionPerformed(evt);
            }
        });

        A_Searchbtn.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        A_Searchbtn.setText("Search");
        A_Searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_SearchbtnActionPerformed(evt);
            }
        });

        D_EditStudent.setFont(new java.awt.Font("Cooper Black", 0, 48)); // NOI18N
        D_EditStudent.setText("Edit Student");

        A_EditBtn.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        A_EditBtn.setText("Edit");
        A_EditBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_EditBtnActionPerformed(evt);
            }
        });

        D_Gender.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_Gender.setText("Gender :");

        D_Email.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_Email.setText("Email :");

        D_Age.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_Age.setText("Age :");

        Email.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        StudentName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        D_ICPassPortNumber.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_ICPassPortNumber.setText("IC/PassPort Number :");

        Age.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        ICPassPortNumber.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        Gender.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        D_Program.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_Program.setText("Program :");

        ProgramComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science (CS)", "Business Information System (BIS)" }));

        D_Intake.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_Intake.setText("Intake : ");

        IntakeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year 1", "Year 2", "Year 3", "Year 4" }));

        D_PhoneNumber.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_PhoneNumber.setText("Phone Number :");

        D_StudentName.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_StudentName.setText("Student Name : ");

        PhoneNumber.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(D_EditStudent)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_StudentName)
                            .addComponent(D_Age)
                            .addComponent(D_Gender)
                            .addComponent(D_PhoneNumber)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(D_Program, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(D_Intake))
                            .addComponent(D_Email)
                            .addComponent(D_ICPassPortNumber))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Gender)
                            .addComponent(StudentName)
                            .addComponent(Age)
                            .addComponent(ProgramComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IntakeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PhoneNumber)
                            .addComponent(Email)
                            .addComponent(ICPassPortNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(D_EnterStudentID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(A_Searchbtn)
                            .addComponent(StudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(249, 249, 249)
                .addComponent(A_EditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(A_Backbtn)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(D_EditStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D_EnterStudentID)
                    .addComponent(StudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(A_Searchbtn)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(D_StudentName)
                    .addComponent(StudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(D_Age)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(D_ICPassPortNumber))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ICPassPortNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D_Gender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(D_PhoneNumber)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_Email)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D_Program, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProgramComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D_Intake, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IntakeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(A_Backbtn)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(A_EditBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(39, Short.MAX_VALUE))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentIDActionPerformed

    private void A_BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_BackbtnActionPerformed
        ManageStudentEnrolment mse = new ManageStudentEnrolment();
        mse.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_A_BackbtnActionPerformed

    private void A_SearchbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_SearchbtnActionPerformed
        String studentid = StudentID.getText().toString();
        String temp =  "Studenttext.txt";
        String Filename = "StudentDetails.txt";
        File tempfile = new File(temp);
        
        if (!studentid.equals("")) {
            String student ="";
            String rl = null;
            StringBuilder bf = new StringBuilder();
            try {
                FileReader fr = new FileReader(Filename);
                BufferedReader br= new BufferedReader(fr);
                while((rl=br.readLine())!= null){
                    rl=rl.trim();
                    if(rl.indexOf(studentid) != -1){bf.append(rl).append("\r\n");}
                }
                br.close();
                FileWriter fw =new FileWriter(temp);
                BufferedWriter bw = new BufferedWriter(fw);
                bw.write(bf.toString());
                bw.flush();
                bw.close();

                Scanner inFile1 = new Scanner(new File(temp)).useDelimiter("  ");
                List<String> temps = new ArrayList<String>();
                while (inFile1.hasNext()) {

                    student = inFile1.next();
                    temps.add(student);
                  }
                  inFile1.close();

                  String[] tempsArray = temps.toArray(new String[0]);

                  StudentName.setText(tempsArray[1]);
                  Age.setText(tempsArray[2]);
                  ICPassPortNumber.setText(tempsArray[3]); 
                  Gender.setText(tempsArray[4]);
                  PhoneNumber.setText(tempsArray[5]);
                  Email.setText(tempsArray[6]);
                  JOptionPane.showMessageDialog(rootPane, "Student Found!");

            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, "Student Not Found!\n Pls Try Again!");
            } 
        } else { JOptionPane.showMessageDialog(rootPane, "Student Not Found!\n Pls Try Again!");}

    }//GEN-LAST:event_A_SearchbtnActionPerformed

    private void A_EditBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_EditBtnActionPerformed
        
        Student_Class sc = new Student_Class();
        String edit = StudentID.getText();
        
        String a = IntakeComboBox.getSelectedItem().toString();
        String b = ICPassPortNumber.getText();        
  
        sc.setName(StudentName.getText());
        sc.setAge(Age.getText());
        sc.setID(StudentID.getText());
        sc.setIC_PP(ICPassPortNumber.getText());
        sc.setGender(Gender.getText());
        sc.setPhoneNumber(PhoneNumber.getText());       
        sc.setEmail(Email.getText());
        sc.setProgram(ProgramComboBox.getSelectedItem().toString());
        sc.setIntake(IntakeComboBox.getSelectedItem().toString());
        
        try{
            sc.EditStudent(edit);
            JOptionPane.showMessageDialog(rootPane, "Edit Success");
            StudentID.setText("");
            StudentName.setText("");
            Age.setText("");
            ICPassPortNumber.setText(""); 
            Gender.setText("");
            PhoneNumber.setText("");
            Email.setText("");        
        }
            
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error");
        }         
    }//GEN-LAST:event_A_EditBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_Backbtn;
    private javax.swing.JButton A_EditBtn;
    private javax.swing.JButton A_Searchbtn;
    private javax.swing.JTextField Age;
    private javax.swing.JLabel D_Age;
    private javax.swing.JLabel D_EditStudent;
    private javax.swing.JLabel D_Email;
    private javax.swing.JLabel D_EnterStudentID;
    private javax.swing.JLabel D_Gender;
    private javax.swing.JLabel D_ICPassPortNumber;
    private javax.swing.JLabel D_Intake;
    private javax.swing.JLabel D_PhoneNumber;
    private javax.swing.JLabel D_Program;
    private javax.swing.JLabel D_StudentName;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Gender;
    private javax.swing.JTextField ICPassPortNumber;
    private javax.swing.JComboBox<String> IntakeComboBox;
    private javax.swing.JTextField PhoneNumber;
    private javax.swing.JComboBox<String> ProgramComboBox;
    private javax.swing.JTextField StudentID;
    private javax.swing.JTextField StudentName;
    // End of variables declaration//GEN-END:variables
}
