
package assignment;

import Assignment_Class.Admin_Class;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.Calendar;

public class Login_Administrators extends javax.swing.JFrame {

    public Login_Administrators() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        A_Password = new javax.swing.JPasswordField();
        D_AdminUserID = new javax.swing.JLabel();
        A_UserID = new javax.swing.JTextField();
        D_AdminPassword = new javax.swing.JLabel();
        D_AdminLogIn = new javax.swing.JLabel();
        D_Admin = new javax.swing.JLabel();
        A_EnterBtn = new javax.swing.JButton();
        A_BackBtn = new javax.swing.JButton();
        A_ClearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        A_Password.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N

        D_AdminUserID.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        D_AdminUserID.setText("User ID :");

        A_UserID.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        A_UserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_UserIDActionPerformed(evt);
            }
        });

        D_AdminPassword.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        D_AdminPassword.setText("Password :");

        D_AdminLogIn.setFont(new java.awt.Font("Cooper Black", 0, 48)); // NOI18N
        D_AdminLogIn.setText("LOGIN");

        D_Admin.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        D_Admin.setText("Academic Administrators");

        A_EnterBtn.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        A_EnterBtn.setText("Enter");
        A_EnterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_EnterBtnActionPerformed(evt);
            }
        });

        A_BackBtn.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        A_BackBtn.setText("Back");
        A_BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_BackBtnActionPerformed(evt);
            }
        });

        A_ClearBtn.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        A_ClearBtn.setText("Clear");
        A_ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_ClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(368, 368, 368)
                        .addComponent(D_AdminLogIn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(D_Admin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_AdminPassword)
                            .addComponent(D_AdminUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(A_UserID)
                            .addComponent(A_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(226, 226, 226)
                        .addComponent(A_BackBtn)
                        .addGap(53, 53, 53)
                        .addComponent(A_EnterBtn)
                        .addGap(57, 57, 57)
                        .addComponent(A_ClearBtn)))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(84, 84, 84)
                .addComponent(D_AdminLogIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(D_Admin)
                .addGap(64, 64, 64)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D_AdminUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A_UserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D_AdminPassword)
                    .addComponent(A_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(A_EnterBtn)
                    .addComponent(A_BackBtn)
                    .addComponent(A_ClearBtn))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void A_BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_BackBtnActionPerformed
            Main_Page mp= new Main_Page();
            mp.setVisible(true);
            this.setVisible(false);        
    }//GEN-LAST:event_A_BackBtnActionPerformed

    private void A_ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_ClearBtnActionPerformed
        A_UserID.setText("");
        A_Password.setText("");
    }//GEN-LAST:event_A_ClearBtnActionPerformed

    private void A_EnterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_EnterBtnActionPerformed

            String username = A_UserID.getText();
            String password = A_Password.getText();
            
            Admin_Class ac = new Admin_Class(username,password);
            
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            Calendar cal = Calendar.getInstance();
            String time = dateFormat.format(cal.getTime());
            
            if(ac.AuthorizeLogin()){
                
                Administrator_Page ap= new Administrator_Page();
                JOptionPane.showMessageDialog(rootPane, "Welcome Administrator " +"\n"+time);
                ap.setVisible(true);
                this.setVisible(false);
                
            }
            else{
                JOptionPane.showMessageDialog(this,"Error UserName or PassWord","Error Message Box",JOptionPane.ERROR_MESSAGE);
            }
                   
    }//GEN-LAST:event_A_EnterBtnActionPerformed

    private void A_UserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_UserIDActionPerformed
         
                              
    }//GEN-LAST:event_A_UserIDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login_Administrators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login_Administrators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login_Administrators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login_Administrators.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login_Administrators().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_BackBtn;
    private javax.swing.JButton A_ClearBtn;
    private javax.swing.JButton A_EnterBtn;
    private javax.swing.JPasswordField A_Password;
    private javax.swing.JTextField A_UserID;
    private javax.swing.JLabel D_Admin;
    private javax.swing.JLabel D_AdminLogIn;
    private javax.swing.JLabel D_AdminPassword;
    private javax.swing.JLabel D_AdminUserID;
    // End of variables declaration//GEN-END:variables
}
