
package assignment;

import Assignment_Class.Educator_Class;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

public class LogIn_Educator extends javax.swing.JFrame {

    /**
     * Creates new form LogIn
     */
    public LogIn_Educator() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        D_EducatorUserID = new javax.swing.JLabel();
        E_UserID = new javax.swing.JTextField();
        D_EducatorPassword = new javax.swing.JLabel();
        D_EducatorLogIn = new javax.swing.JLabel();
        D_Educator = new javax.swing.JLabel();
        E_Password = new javax.swing.JPasswordField();
        E_EnterBtn = new javax.swing.JButton();
        E_BackBtn = new javax.swing.JButton();
        E_ClearBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        D_EducatorUserID.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        D_EducatorUserID.setText("User ID :");

        E_UserID.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        E_UserID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_UserIDActionPerformed(evt);
            }
        });

        D_EducatorPassword.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        D_EducatorPassword.setText("Password :");

        D_EducatorLogIn.setFont(new java.awt.Font("Cooper Black", 0, 48)); // NOI18N
        D_EducatorLogIn.setText("LOGIN");

        D_Educator.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        D_Educator.setText("Educator");

        E_Password.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N

        E_EnterBtn.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        E_EnterBtn.setText("Enter");
        E_EnterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_EnterBtnActionPerformed(evt);
            }
        });

        E_BackBtn.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        E_BackBtn.setText("Back");
        E_BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_BackBtnActionPerformed(evt);
            }
        });

        E_ClearBtn.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        E_ClearBtn.setText("Clear");
        E_ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_ClearBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(415, 415, 415)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_EducatorLogIn)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(D_Educator))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(E_BackBtn)
                                .addGap(53, 53, 53)
                                .addComponent(E_EnterBtn)
                                .addGap(57, 57, 57)
                                .addComponent(E_ClearBtn)
                                .addGap(18, 18, 18))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(D_EducatorPassword)
                                    .addComponent(D_EducatorUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(E_UserID)
                                    .addComponent(E_Password, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(317, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(D_EducatorLogIn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(D_Educator)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D_EducatorUserID, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E_UserID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D_EducatorPassword)
                    .addComponent(E_Password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(57, 57, 57)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E_EnterBtn)
                    .addComponent(E_BackBtn)
                    .addComponent(E_ClearBtn))
                .addContainerGap(118, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void E_BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_BackBtnActionPerformed
            Main_Page mp= new Main_Page();
            mp.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_E_BackBtnActionPerformed

    private void E_ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_ClearBtnActionPerformed
        E_UserID.setText("");
        E_Password.setText("");
    }//GEN-LAST:event_E_ClearBtnActionPerformed

    private void E_UserIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_UserIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_E_UserIDActionPerformed

    private void E_EnterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_EnterBtnActionPerformed
            String username = E_UserID.getText();
            String password = E_Password.getText();
            
            Educator_Class ec = new Educator_Class(username,password);
            
            DateFormat dateFormat = new SimpleDateFormat("yyyy/MM/dd HH:mm:ss");
            java.util.Calendar cal = java.util.Calendar.getInstance();
            String time = dateFormat.format(cal.getTime());
            
            if(ec.AuthorizeLogin()){
                
                Educator_Page ep= new Educator_Page();
                JOptionPane.showMessageDialog(rootPane, "Welcome Educator" +"\n"+time);
                ep.setVisible(true);
                this.setVisible(false);              
            }
            else{
                JOptionPane.showMessageDialog(this,"Error UserName or PassWord","Error Message Box",JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_E_EnterBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogIn_Educator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogIn_Educator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogIn_Educator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogIn_Educator.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogIn_Educator().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel D_Educator;
    private javax.swing.JLabel D_EducatorLogIn;
    private javax.swing.JLabel D_EducatorPassword;
    private javax.swing.JLabel D_EducatorUserID;
    private javax.swing.JButton E_BackBtn;
    private javax.swing.JButton E_ClearBtn;
    private javax.swing.JButton E_EnterBtn;
    private javax.swing.JPasswordField E_Password;
    private javax.swing.JTextField E_UserID;
    // End of variables declaration//GEN-END:variables
}
