
package assignment;

public class Main_Page extends javax.swing.JFrame {

    /**
     * Creates new form Main_Page
     */
    public Main_Page() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jRadioButton1 = new javax.swing.JRadioButton();
        Admin_Btn = new javax.swing.JButton();
        D_SystemTitle = new javax.swing.JLabel();
        Educator_Btn = new javax.swing.JButton();
        MainExit_Btn = new javax.swing.JLabel();
        MP_Exitbtn = new javax.swing.JButton();

        jRadioButton1.setText("jRadioButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Admin_Btn.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        Admin_Btn.setText("Administrator");
        Admin_Btn.setToolTipText("");
        Admin_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_BtnActionPerformed(evt);
            }
        });

        D_SystemTitle.setFont(new java.awt.Font("Cooper Black", 0, 48)); // NOI18N
        D_SystemTitle.setText("ACADEMIC COURSEWORK REPORT SYSTEM");

        Educator_Btn.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        Educator_Btn.setText("Educator");
        Educator_Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Educator_BtnActionPerformed(evt);
            }
        });

        MainExit_Btn.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N

        MP_Exitbtn.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        MP_Exitbtn.setText("Exit");
        MP_Exitbtn.setActionCommand("Exit");
        MP_Exitbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MP_ExitbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(244, 244, 244)
                                .addComponent(Admin_Btn)
                                .addGap(220, 220, 220)
                                .addComponent(Educator_Btn))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addComponent(D_SystemTitle)))
                        .addGap(0, 130, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(MainExit_Btn)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MP_Exitbtn))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(D_SystemTitle)
                .addGap(187, 187, 187)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Admin_Btn)
                    .addComponent(Educator_Btn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                .addComponent(MainExit_Btn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(MP_Exitbtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Admin_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_BtnActionPerformed
            Login_Administrators la= new Login_Administrators();
            la.setVisible(true);
            this.setVisible(false);
    }//GEN-LAST:event_Admin_BtnActionPerformed

    private void Educator_BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Educator_BtnActionPerformed
            LogIn_Educator le= new LogIn_Educator();
            le.setVisible(true);
            this.setVisible(false);        
    }//GEN-LAST:event_Educator_BtnActionPerformed

    private void MP_ExitbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MP_ExitbtnActionPerformed
        System.exit(0);
    }//GEN-LAST:event_MP_ExitbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main_Page.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main_Page().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Admin_Btn;
    private javax.swing.JLabel D_SystemTitle;
    private javax.swing.JButton Educator_Btn;
    private javax.swing.JButton MP_Exitbtn;
    private javax.swing.JLabel MainExit_Btn;
    private javax.swing.JRadioButton jRadioButton1;
    // End of variables declaration//GEN-END:variables
}
