package assignment;

public class ManageStudentEnrolment extends javax.swing.JFrame {

    /**
     * Creates new form ManageStudentEnrolment
     */
    public ManageStudentEnrolment() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        S_Backbtn = new javax.swing.JButton();
        D_RegisterBtn = new javax.swing.JButton();
        D_RemoveStudentBtn = new javax.swing.JButton();
        D_EditStudentDetailBtn = new javax.swing.JButton();
        D_CheckStudentDetail = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        jLabel1.setText("Manage Student Enrolment");

        S_Backbtn.setFont(new java.awt.Font("Cooper Black", 0, 12)); // NOI18N
        S_Backbtn.setText("Back");
        S_Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                S_BackbtnActionPerformed(evt);
            }
        });

        D_RegisterBtn.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_RegisterBtn.setText("Register");
        D_RegisterBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_RegisterBtnActionPerformed(evt);
            }
        });

        D_RemoveStudentBtn.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_RemoveStudentBtn.setText("Remove Student");
        D_RemoveStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_RemoveStudentBtnActionPerformed(evt);
            }
        });

        D_EditStudentDetailBtn.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_EditStudentDetailBtn.setText("Edit Student Detail");
        D_EditStudentDetailBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_EditStudentDetailBtnActionPerformed(evt);
            }
        });

        D_CheckStudentDetail.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_CheckStudentDetail.setText("Check Student Detail");
        D_CheckStudentDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_CheckStudentDetailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_RegisterBtn)
                            .addComponent(D_RemoveStudentBtn)
                            .addComponent(D_EditStudentDetailBtn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(D_CheckStudentDetail)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(S_Backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel1)))
                .addContainerGap(72, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(20, 20, 20)
                .addComponent(D_RegisterBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(D_EditStudentDetailBtn)
                .addGap(7, 7, 7)
                .addComponent(D_RemoveStudentBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D_CheckStudentDetail)
                    .addComponent(S_Backbtn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void S_BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_S_BackbtnActionPerformed
        Administrator_Page ap = new Administrator_Page();
        ap.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_S_BackbtnActionPerformed

    private void D_RegisterBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_RegisterBtnActionPerformed
        RegisterStudent rs= new RegisterStudent();
        rs.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D_RegisterBtnActionPerformed

    private void D_RemoveStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_RemoveStudentBtnActionPerformed
        RemoveStudent rm= new RemoveStudent();
        rm.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D_RemoveStudentBtnActionPerformed

    private void D_EditStudentDetailBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_EditStudentDetailBtnActionPerformed
        EditStudent es= new EditStudent();
        es.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D_EditStudentDetailBtnActionPerformed

    private void D_CheckStudentDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_CheckStudentDetailActionPerformed
        CheckStudentDetail csd= new CheckStudentDetail();
        csd.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D_CheckStudentDetailActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageStudentEnrolment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageStudentEnrolment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageStudentEnrolment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageStudentEnrolment.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageStudentEnrolment().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton D_CheckStudentDetail;
    private javax.swing.JButton D_EditStudentDetailBtn;
    private javax.swing.JButton D_RegisterBtn;
    private javax.swing.JButton D_RemoveStudentBtn;
    private javax.swing.JButton S_Backbtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
