
package assignment;

import Assignment_Class.Mark_Class;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Mark_Entry extends javax.swing.JFrame {

    /**
     * Creates new form Mark_Entry
     */
    public Mark_Entry() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        QuizMark = new javax.swing.JTextField();
        D_MOduleName = new javax.swing.JLabel();
        ChooseIntake = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ShowModule = new javax.swing.JTextArea();
        D_StidentID = new javax.swing.JLabel();
        D_Intake = new javax.swing.JLabel();
        D_ComfirmBtn = new javax.swing.JButton();
        A_SearchBtn = new javax.swing.JButton();
        D_Comment = new javax.swing.JLabel();
        D_Program = new javax.swing.JLabel();
        D_Quiz = new javax.swing.JLabel();
        ChooseProgram = new javax.swing.JComboBox<>();
        Comment = new javax.swing.JTextField();
        D_ClearBtn = new javax.swing.JButton();
        D_LabTest = new javax.swing.JLabel();
        D_MarkEntry = new javax.swing.JLabel();
        A_Backbtn = new javax.swing.JButton();
        D_Asgn = new javax.swing.JLabel();
        AssignmentMark = new javax.swing.JTextField();
        ModuleName = new javax.swing.JTextField();
        StudentID = new javax.swing.JTextField();
        LabTestMark = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        D_MOduleName.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_MOduleName.setText("Module Name :");

        ChooseIntake.setFont(new java.awt.Font("Cooper Black", 0, 16)); // NOI18N
        ChooseIntake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year 1", "Year 2", "Year 3", "Year 4" }));
        ChooseIntake.setToolTipText("");

        ShowModule.setColumns(20);
        ShowModule.setRows(5);
        jScrollPane1.setViewportView(ShowModule);

        D_StidentID.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_StidentID.setText("Student ID :");

        D_Intake.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_Intake.setText("Intake : ");

        D_ComfirmBtn.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_ComfirmBtn.setText("Comfirm");
        D_ComfirmBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_ComfirmBtnActionPerformed(evt);
            }
        });

        A_SearchBtn.setFont(new java.awt.Font("Cooper Black", 0, 16)); // NOI18N
        A_SearchBtn.setText("Search");
        A_SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_SearchBtnActionPerformed(evt);
            }
        });

        D_Comment.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_Comment.setText("Comment :");

        D_Program.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_Program.setText("Program :");

        D_Quiz.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_Quiz.setText("Quiz Mark (10%) :");

        ChooseProgram.setFont(new java.awt.Font("Cooper Black", 0, 16)); // NOI18N
        ChooseProgram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science (CS)", "Business Information System (BIS)" }));
        ChooseProgram.setToolTipText("");

        Comment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CommentActionPerformed(evt);
            }
        });

        D_ClearBtn.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_ClearBtn.setText("Clear");
        D_ClearBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_ClearBtnActionPerformed(evt);
            }
        });

        D_LabTest.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_LabTest.setText("Lab Test Mark (40%) :");

        D_MarkEntry.setFont(new java.awt.Font("Cooper Black", 0, 48)); // NOI18N
        D_MarkEntry.setText("Mark Entry ");

        A_Backbtn.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        A_Backbtn.setText("Back");
        A_Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_BackbtnActionPerformed(evt);
            }
        });

        D_Asgn.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_Asgn.setText("Assignment Mark (50%) :");

        LabTestMark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LabTestMarkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(D_MarkEntry, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(D_StidentID, javax.swing.GroupLayout.PREFERRED_SIZE, 318, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(StudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(D_MOduleName, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(ModuleName, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(D_Program)
                                    .addComponent(D_Intake))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChooseIntake, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ChooseProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(A_SearchBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(D_Comment, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(Comment, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(D_Asgn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(D_LabTest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(D_Quiz, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(A_Backbtn))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(D_ClearBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(D_ComfirmBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(QuizMark)
                                .addComponent(LabTestMark)
                                .addComponent(AssignmentMark, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(D_MarkEntry)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(D_Program)
                            .addComponent(ChooseProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(D_Intake)
                            .addComponent(ChooseIntake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(A_SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D_MOduleName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModuleName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(D_StidentID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(D_Quiz, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D_LabTest, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D_Asgn, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(QuizMark, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabTestMark, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(AssignmentMark, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(D_Comment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(125, 125, 125)
                        .addComponent(A_Backbtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addComponent(Comment, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_ClearBtn)
                            .addComponent(D_ComfirmBtn))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void D_ComfirmBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_ComfirmBtnActionPerformed

        int Quiz = 0, LabTest = 0, Assignment = 0;
        Mark_Class mC= new Mark_Class();
        mC.setQuiz(Integer.parseInt(QuizMark.getText()));
        mC.setLabTest(Integer.parseInt(LabTestMark.getText()));
        mC.setAssignment(Integer.parseInt(AssignmentMark.getText()));

        mC.setProgram(ChooseProgram.getSelectedItem().toString());
        mC.setIntake(ChooseIntake.getSelectedItem().toString());
        mC.setModule(ModuleName.getText());
        mC.setStudentid(StudentID.getText());

        mC.setComment(Comment.getText());

        mC.markEntry(mC.checkMark());

    }//GEN-LAST:event_D_ComfirmBtnActionPerformed

    private void A_SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_SearchBtnActionPerformed

        String program = ChooseProgram.getSelectedItem().toString();
        String intake = ChooseIntake.getSelectedItem().toString();
        String temp =  "text.txt";
        String Filename =  program + ".txt";
        File tempfile = new File(temp);

        String rl=null;
        StringBuilder bf = new StringBuilder();
        try {
            FileReader fr = new FileReader(Filename);
            BufferedReader br= new BufferedReader(fr);
            while((rl=br.readLine())!= null){
                rl=rl.trim();
                if(rl.indexOf(intake) != -1){bf.append(rl).append("\r\n");}
            }
            br.close();
            FileWriter fw =new FileWriter(temp);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(bf.toString());
            bw.flush();
            bw.close();
            FileReader fr2 = new FileReader(new File(temp));
            BufferedReader br2 =new BufferedReader(fr2);
            ShowModule.read(br2, null);
            br.close();
            ShowModule.requestFocus();
            tempfile.delete();

        } catch (IOException ex) {
            Logger.getLogger(DeleteModule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_A_SearchBtnActionPerformed

    private void CommentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CommentActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CommentActionPerformed

    private void D_ClearBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_ClearBtnActionPerformed
        ModuleName.setText("");
        StudentID.setText("");

        QuizMark.setText("");
        LabTestMark.setText("");
        AssignmentMark.setText("");
        Comment.setText("");
    }//GEN-LAST:event_D_ClearBtnActionPerformed

    private void A_BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_BackbtnActionPerformed
        Educator_Page ep = new Educator_Page();
        ep.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_A_BackbtnActionPerformed

    private void LabTestMarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LabTestMarkActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LabTestMarkActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mark_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mark_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mark_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mark_Entry.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mark_Entry().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_Backbtn;
    private javax.swing.JButton A_SearchBtn;
    private javax.swing.JTextField AssignmentMark;
    private javax.swing.JComboBox<String> ChooseIntake;
    private javax.swing.JComboBox<String> ChooseProgram;
    private javax.swing.JTextField Comment;
    private javax.swing.JLabel D_Asgn;
    private javax.swing.JButton D_ClearBtn;
    private javax.swing.JButton D_ComfirmBtn;
    private javax.swing.JLabel D_Comment;
    private javax.swing.JLabel D_Intake;
    private javax.swing.JLabel D_LabTest;
    private javax.swing.JLabel D_MOduleName;
    private javax.swing.JLabel D_MarkEntry;
    private javax.swing.JLabel D_Program;
    private javax.swing.JLabel D_Quiz;
    private javax.swing.JLabel D_StidentID;
    private javax.swing.JTextField LabTestMark;
    private javax.swing.JTextField ModuleName;
    private javax.swing.JTextField QuizMark;
    private javax.swing.JTextArea ShowModule;
    private javax.swing.JTextField StudentID;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
