package assignment;

import com.itextpdf.text.BaseColor;
import com.itextpdf.text.DocumentException;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfWriter;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import  com.itextpdf.text.Document;
import com.itextpdf.text.Phrase;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import java.util.Scanner;
import java.util.stream.Stream;
import javax.swing.JOptionPane;

public class ModuleReport extends javax.swing.JFrame {

    /**
     * Creates new form PrintReport
     */
    public ModuleReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        D_PrintReport = new javax.swing.JLabel();
        E_PrintBtn = new javax.swing.JButton();
        ChooseProgram = new javax.swing.JComboBox<>();
        D_Program = new javax.swing.JLabel();
        A_SearchBtn = new javax.swing.JButton();
        D_Intake = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        ShowModule = new javax.swing.JTextArea();
        ChooseIntake = new javax.swing.JComboBox<>();
        D_MOduleName = new javax.swing.JLabel();
        ModuleName = new javax.swing.JTextField();
        A_Backbtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        D_PrintReport.setFont(new java.awt.Font("Cooper Black", 0, 36)); // NOI18N
        D_PrintReport.setText("Print Report");

        E_PrintBtn.setFont(new java.awt.Font("Cooper Black", 0, 16)); // NOI18N
        E_PrintBtn.setText("Print");
        E_PrintBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E_PrintBtnActionPerformed(evt);
            }
        });

        ChooseProgram.setFont(new java.awt.Font("Cooper Black", 0, 16)); // NOI18N
        ChooseProgram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science (CS)", "Business Information System (BIS)" }));
        ChooseProgram.setToolTipText("");

        D_Program.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_Program.setText("Program :");

        A_SearchBtn.setFont(new java.awt.Font("Cooper Black", 0, 16)); // NOI18N
        A_SearchBtn.setText("Search");
        A_SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_SearchBtnActionPerformed(evt);
            }
        });

        D_Intake.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_Intake.setText("Intake : ");

        ShowModule.setColumns(20);
        ShowModule.setRows(5);
        jScrollPane1.setViewportView(ShowModule);

        ChooseIntake.setFont(new java.awt.Font("Cooper Black", 0, 16)); // NOI18N
        ChooseIntake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year 1", "Year 2", "Year 3", "Year 4" }));
        ChooseIntake.setToolTipText("");

        D_MOduleName.setFont(new java.awt.Font("Cooper Black", 0, 24)); // NOI18N
        D_MOduleName.setText("Module Name :");

        A_Backbtn.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        A_Backbtn.setText("Back");
        A_Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_BackbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(D_MOduleName, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(ModuleName, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(D_Program)
                                            .addComponent(D_Intake))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(ChooseIntake, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(ChooseProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addComponent(A_SearchBtn, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(D_PrintReport, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(A_Backbtn)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(E_PrintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(140, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(D_PrintReport, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(D_Program)
                            .addComponent(ChooseProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(D_Intake)
                            .addComponent(ChooseIntake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(A_SearchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D_MOduleName, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ModuleName, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(E_PrintBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(A_Backbtn))
                .addContainerGap(77, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void E_PrintBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E_PrintBtnActionPerformed
      boolean status = false;
      try {
            
            String PDFlist[] = new String[20];
            String module = ModuleName.getText();
            Document document = new Document();
            PdfWriter.getInstance(document, new FileOutputStream(module +".pdf"));
            Scanner PDFStudent = new Scanner(new File("StudentMarks.txt"));
            document.open();
            
            while(PDFStudent.hasNextLine()){
                String PdfAll = PDFStudent.nextLine();
                String[] PDF = PdfAll.split(", ", 0);
                if(module.equalsIgnoreCase(PDF[4])){               

                    PDFlist[2]=PDF[2];
                    PDFlist[3]=PDF[3];
                    PDFlist[4]=PDF[4];
                    status=true;
                }
            }
            
            if (status) {
                document.add(new Paragraph("Module Overall Student Report"));
                document.add(new Paragraph("--------------------------------------------------------------------"));

                document.add(new Paragraph("Program: " + PDFlist[2]));
                document.add(new Paragraph("INTAKE: " + PDFlist[3]));
                document.add(new Paragraph("Module : " + PDFlist[4]));
                document.add(new Paragraph("\n" ));

                PdfPTable table = new PdfPTable(7);


                addTableHeader(table);
                addRows(table);

                document.add(table);
                document.close();
                JOptionPane.showMessageDialog(null, "Report Print Success","Comfirmation Message",JOptionPane.INFORMATION_MESSAGE);
                
                } else {
                    JOptionPane.showMessageDialog(null, "Module not found","Error Message",JOptionPane.INFORMATION_MESSAGE);
                }
        } 
      catch (DocumentException ignore) {}
      catch (FileNotFoundException e){}
    }
    
    private static void addTableHeader(PdfPTable table) {
        Stream.of("Student Id", "Name", "QUIZ MARK", "LAB TEST MARK", "ASSIGNMENT MARK", "FINAL MARK", "COMMENT")
        .forEach(columnTitle -> {
        PdfPCell header = new PdfPCell();
        header.setBackgroundColor(BaseColor.LIGHT_GRAY);
        header.setBorderWidth(1);
        header.setPhrase(new Phrase(columnTitle));
        table.addCell(header);
        });
    }
        
    private void addRows(PdfPTable table) {
        try {
            Scanner c = new Scanner(new File("StudentMarks.txt"));
            String student1 = ModuleName.getText();
            while(c.hasNextLine()){
                String StudentDetail =  c.nextLine();
                String[] temp = StudentDetail.split(", ", 0);
                if(student1.equalsIgnoreCase(temp[4])){
                    table.addCell(temp[0]);
                    table.addCell(temp[1]);
                    table.addCell(temp[5]);
                    table.addCell(temp[6]);
                    table.addCell(temp[7]);
                    table.addCell(temp[8]);
                    table.addCell(temp[9]);
                }    
            }
        }
        catch (FileNotFoundException ex) {
        }

    }//GEN-LAST:event_E_PrintBtnActionPerformed

    private void A_SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_SearchBtnActionPerformed

        String program = ChooseProgram.getSelectedItem().toString();
        String intake = ChooseIntake.getSelectedItem().toString();
        String temp =  "text.txt";
        String Filename = program + ".txt";
        File tempfile = new File(temp);

        String rl=null;
        StringBuilder bf = new StringBuilder();
        try {
            FileReader fr = new FileReader(Filename);
            BufferedReader br= new BufferedReader(fr);
            while((rl=br.readLine())!= null){
                rl=rl.trim();
                if(rl.indexOf(intake) != -1){bf.append(rl).append("\r\n");}
            }
            br.close();
            FileWriter fw =new FileWriter(temp);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(bf.toString());
            bw.flush();
            bw.close();
            FileReader fr2 = new FileReader(new File(temp));
            BufferedReader br2 =new BufferedReader(fr2);
            ShowModule.read(br2, null);
            br.close();
            ShowModule.requestFocus();
            tempfile.delete();

        } catch (IOException ex) {
            Logger.getLogger(DeleteModule.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_A_SearchBtnActionPerformed

    private void A_BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_BackbtnActionPerformed
        Educator_Page ep = new Educator_Page();
        ep.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_A_BackbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModuleReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModuleReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModuleReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModuleReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModuleReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_Backbtn;
    private javax.swing.JButton A_SearchBtn;
    private javax.swing.JComboBox<String> ChooseIntake;
    private javax.swing.JComboBox<String> ChooseProgram;
    private javax.swing.JLabel D_Intake;
    private javax.swing.JLabel D_MOduleName;
    private javax.swing.JLabel D_PrintReport;
    private javax.swing.JLabel D_Program;
    private javax.swing.JButton E_PrintBtn;
    private javax.swing.JTextField ModuleName;
    private javax.swing.JTextArea ShowModule;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
