package assignment;

import Assignment_Class.Student_Class;
import javax.swing.JOptionPane;
import java.util.Random;

public class RegisterStudent extends javax.swing.JFrame {

    /**
     * Creates new form RegisterStudent
     */
    public RegisterStudent() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        D_StudentRegister = new javax.swing.JLabel();
        D_StudentName = new javax.swing.JLabel();
        D_Gender = new javax.swing.JLabel();
        D_Age = new javax.swing.JLabel();
        StudentName = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        Gender = new javax.swing.JTextField();
        D_Program = new javax.swing.JLabel();
        ProgramComboBox = new javax.swing.JComboBox<>();
        D_Intake = new javax.swing.JLabel();
        IntakeComboBox = new javax.swing.JComboBox<>();
        D_PhoneNumber = new javax.swing.JLabel();
        PhoneNumber = new javax.swing.JTextField();
        D_Email = new javax.swing.JLabel();
        Email = new javax.swing.JTextField();
        D_ICPassPortNumber = new javax.swing.JLabel();
        ICPassPortNumber = new javax.swing.JTextField();
        D_Register = new javax.swing.JButton();
        D_Clear = new javax.swing.JButton();
        D_Back = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        D_StudentRegister.setFont(new java.awt.Font("Cooper Black", 0, 48)); // NOI18N
        D_StudentRegister.setText("Student Register");

        D_StudentName.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_StudentName.setText("Student Name : ");

        D_Gender.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_Gender.setText("Gender :");

        D_Age.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_Age.setText("Age :");

        StudentName.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        Age.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        Gender.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        D_Program.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_Program.setText("Program :");

        ProgramComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science (CS)", "Business Information System (BIS)" }));

        D_Intake.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_Intake.setText("Intake : ");

        IntakeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year 1", "Year 2", "Year 3", "Year 4" }));

        D_PhoneNumber.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_PhoneNumber.setText("Phone Number :");

        PhoneNumber.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        D_Email.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_Email.setText("Email :");

        Email.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        D_ICPassPortNumber.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_ICPassPortNumber.setText("IC/PassPort Number :");

        ICPassPortNumber.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N

        D_Register.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_Register.setText("Register");
        D_Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_RegisterActionPerformed(evt);
            }
        });

        D_Clear.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        D_Clear.setText("Clear");
        D_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_ClearActionPerformed(evt);
            }
        });

        D_Back.setFont(new java.awt.Font("Cooper Black", 0, 14)); // NOI18N
        D_Back.setText("Back");
        D_Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D_BackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_StudentName)
                            .addComponent(D_Age)
                            .addComponent(D_Gender)
                            .addComponent(D_PhoneNumber)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(D_Program, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(D_Intake))
                            .addComponent(D_Email)
                            .addComponent(D_ICPassPortNumber))
                        .addGap(74, 74, 74)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Gender)
                            .addComponent(StudentName, javax.swing.GroupLayout.DEFAULT_SIZE, 290, Short.MAX_VALUE)
                            .addComponent(Age)
                            .addComponent(ProgramComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(IntakeComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(PhoneNumber)
                            .addComponent(Email)
                            .addComponent(ICPassPortNumber)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(D_Clear, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 27, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(D_StudentRegister))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(D_Back, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(252, 252, 252)
                        .addComponent(D_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(D_StudentRegister)
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(D_StudentName)
                    .addComponent(StudentName, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(D_Age)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(D_ICPassPortNumber))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Age, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ICPassPortNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(D_Gender))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(D_PhoneNumber)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(PhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_Email)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D_Program, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ProgramComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D_Intake, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(IntakeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(D_Clear)
                .addGap(30, 30, 30)
                .addComponent(D_Register, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(D_Back)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void D_RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_RegisterActionPerformed
        
        String a = IntakeComboBox.getSelectedItem().toString();
        String b = ICPassPortNumber.getText();
        Random random=new Random();
   
        int stID = 10000 + random.nextInt(10000);
        String StudentID = "TP0" + a.charAt(5)+ stID ;

        Student_Class sc = new Student_Class();
        sc.setID(StudentID);
        sc.setName(StudentName.getText());
        sc.setAge(Age.getText());
        sc.setIC_PP(ICPassPortNumber.getText());
        sc.setGender(Gender.getText());
        sc.setPhoneNumber(PhoneNumber.getText());       
        sc.setEmail(Email.getText());
        sc.setProgram(ProgramComboBox.getSelectedItem().toString());
        sc.setIntake(IntakeComboBox.getSelectedItem().toString());
        
        try{
            sc.RegisterStudent();
            JOptionPane.showMessageDialog(rootPane, "Student ID is " + StudentID +"\nRegister Success");
            StudentName.setText("");
            Age.setText("");
            ICPassPortNumber.setText(""); 
            Gender.setText("");
            PhoneNumber.setText("");
            Email.setText("");        
        }
            
        catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Error");
        }
    }//GEN-LAST:event_D_RegisterActionPerformed

    private void D_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_ClearActionPerformed
        StudentName.setText("");
        Age.setText("");
        ICPassPortNumber.setText(""); 
        Gender.setText("");
        PhoneNumber.setText("");
        Email.setText("");
    }//GEN-LAST:event_D_ClearActionPerformed

    private void D_BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D_BackActionPerformed
        ManageStudentEnrolment mse = new ManageStudentEnrolment();
        mse.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_D_BackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegisterStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegisterStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JLabel D_Age;
    private javax.swing.JButton D_Back;
    private javax.swing.JButton D_Clear;
    private javax.swing.JLabel D_Email;
    private javax.swing.JLabel D_Gender;
    private javax.swing.JLabel D_ICPassPortNumber;
    private javax.swing.JLabel D_Intake;
    private javax.swing.JLabel D_PhoneNumber;
    private javax.swing.JLabel D_Program;
    private javax.swing.JButton D_Register;
    private javax.swing.JLabel D_StudentName;
    private javax.swing.JLabel D_StudentRegister;
    private javax.swing.JTextField Email;
    private javax.swing.JTextField Gender;
    private javax.swing.JTextField ICPassPortNumber;
    private javax.swing.JComboBox<String> IntakeComboBox;
    private javax.swing.JTextField PhoneNumber;
    private javax.swing.JComboBox<String> ProgramComboBox;
    private javax.swing.JTextField StudentName;
    // End of variables declaration//GEN-END:variables
}
