
package assignment;

import Assignment_Class.Student_Class;
import java.io.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

public class RemoveStudent extends javax.swing.JFrame {

    /**
     * Creates new form RemoveStudent
     */
    public RemoveStudent() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        D_Intake = new javax.swing.JLabel();
        D_EnterStudentID = new javax.swing.JLabel();
        ChooseIntake = new javax.swing.JComboBox<>();
        StudentID = new javax.swing.JTextField();
        A_Backbtn = new javax.swing.JButton();
        A_Removebtn = new javax.swing.JButton();
        D_RemoveStudent = new javax.swing.JLabel();
        A_ShowStudentBtn = new javax.swing.JButton();
        ChooseProgram = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        ShowStudent = new javax.swing.JTextArea();
        D_Program = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        D_Intake.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_Intake.setText("Intake : ");

        D_EnterStudentID.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_EnterStudentID.setText("Enter Student ID : ");

        ChooseIntake.setFont(new java.awt.Font("Cooper Black", 0, 16)); // NOI18N
        ChooseIntake.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Year 1", "Year 2", "Year 3", "Year 4" }));
        ChooseIntake.setToolTipText("");

        StudentID.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        StudentID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StudentIDActionPerformed(evt);
            }
        });

        A_Backbtn.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        A_Backbtn.setText("Back");
        A_Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_BackbtnActionPerformed(evt);
            }
        });

        A_Removebtn.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        A_Removebtn.setText("Remove");
        A_Removebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_RemovebtnActionPerformed(evt);
            }
        });

        D_RemoveStudent.setFont(new java.awt.Font("Cooper Black", 0, 48)); // NOI18N
        D_RemoveStudent.setText("Remove Student");

        A_ShowStudentBtn.setFont(new java.awt.Font("Cooper Black", 0, 16)); // NOI18N
        A_ShowStudentBtn.setText("Liat All Student");
        A_ShowStudentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A_ShowStudentBtnActionPerformed(evt);
            }
        });

        ChooseProgram.setFont(new java.awt.Font("Cooper Black", 0, 16)); // NOI18N
        ChooseProgram.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Computer Science (CS)", "Business Information System (BIS)" }));
        ChooseProgram.setToolTipText("");

        ShowStudent.setColumns(20);
        ShowStudent.setRows(5);
        jScrollPane1.setViewportView(ShowStudent);

        D_Program.setFont(new java.awt.Font("Cooper Black", 0, 18)); // NOI18N
        D_Program.setText("Program :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(D_RemoveStudent)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(D_Program)
                                    .addComponent(D_Intake))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ChooseIntake, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ChooseProgram, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(633, 633, 633)
                                .addComponent(A_ShowStudentBtn)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(A_Removebtn)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(D_EnterStudentID)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(StudentID, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(A_Backbtn)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(D_RemoveStudent)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D_Program)
                    .addComponent(ChooseProgram, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D_Intake)
                    .addComponent(ChooseIntake, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(A_ShowStudentBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(D_EnterStudentID)
                    .addComponent(StudentID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(A_Removebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(A_Backbtn)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StudentIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StudentIDActionPerformed

    private void A_BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_BackbtnActionPerformed
        ManageStudentEnrolment mse = new ManageStudentEnrolment();
        mse.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_A_BackbtnActionPerformed

    private void A_RemovebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_RemovebtnActionPerformed
        Student_Class sc = new Student_Class();
        String studentid = StudentID.getText();
        
        if (!studentid.equals("")) {
            try {
            Boolean status = sc.RemoveStudent(studentid);
            if (status) {
                JOptionPane.showMessageDialog(rootPane, "Student Removed");
            }
            StudentID.setText("");

        }catch (Exception e) {
            Logger.getLogger(DeleteModule.class.getName()).log(Level.SEVERE, null, e);
        }
        }else{
            JOptionPane.showMessageDialog(null,"Invalid Student ID!\n Please Enter Valid Student ID","Error Message", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_A_RemovebtnActionPerformed

    private void A_ShowStudentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A_ShowStudentBtnActionPerformed

        String program = ChooseProgram.getSelectedItem().toString();
        String intake = ChooseIntake.getSelectedItem().toString();
        String temp =  "Studenttext.txt";
        String Filename = "StudentDetails.txt";
        File tempfile = new File(temp);

        String rl=null;
        StringBuilder bf = new StringBuilder();
        try {
            FileReader fr = new FileReader(Filename);
            BufferedReader br= new BufferedReader(fr);
            while((rl=br.readLine())!= null){
                rl=rl.trim();
                if(rl.indexOf(intake) != -1){bf.append(rl).append("\r\n");}
            }
            br.close();
            FileWriter fw =new FileWriter(temp);
            BufferedWriter bw = new BufferedWriter(fw);
            bw.write(bf.toString());
            bw.flush();
            bw.close();
            FileReader fr2 = new FileReader(new File(temp));
            BufferedReader br2 =new BufferedReader(fr2);
            ShowStudent.read(br2, null);
            br.close();
            ShowStudent.requestFocus();
            tempfile.delete();

        } catch (IOException ex) {
            Logger.getLogger(DeleteModule.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_A_ShowStudentBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RemoveStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RemoveStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RemoveStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RemoveStudent.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RemoveStudent().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A_Backbtn;
    private javax.swing.JButton A_Removebtn;
    private javax.swing.JButton A_ShowStudentBtn;
    private javax.swing.JComboBox<String> ChooseIntake;
    private javax.swing.JComboBox<String> ChooseProgram;
    private javax.swing.JLabel D_EnterStudentID;
    private javax.swing.JLabel D_Intake;
    private javax.swing.JLabel D_Program;
    private javax.swing.JLabel D_RemoveStudent;
    private javax.swing.JTextArea ShowStudent;
    private javax.swing.JTextField StudentID;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
